"""Headless "pure worker": plan a hard task on the heavy model, then drive the
browser autonomously to gather the data and auto-write an executive markdown
report.

Two deterministic phases, no human in the loop:

1. PLAN  -- the ``planner`` roster role (heavy model ``gemma-4-31b-it``) turns the
   objective into a phased, browser-aware execution plan.
2. EXECUTE -- an autonomous ``ChatAgent`` with the browser + write_file tools
   follows the plan, drives Chrome heavily, and writes the report.

Entry points: ``run_worker(task)`` (async) and ``main()`` (CLI /
``supporter-worker``).
"""

from __future__ import annotations

import argparse
import asyncio
import os
import re
import sys
from collections.abc import Callable
from datetime import datetime
from pathlib import Path
from typing import Any

from .agent import ChatAgent
from .config import config
from .llm.types import GenOptions
from .logger import logger
from .pool import get_provider
from .replan import ReplanContext
from .tools import file_ops
from .tools.browser import guardrails
from .tools.browser.session import close_session
from .tools.catalog import build_tool_catalog, select_tools

__all__ = ["sys"]
_EXECUTOR_TOOLS = ("read_file", "write_file", "browse", "web_search")
_MIN_REPORT_BYTES = 200
_DEFAULT_MAX_TURNS = 8

EXECUTOR_SYSTEM_INSTRUCTION = (
    "You are an autonomous browser worker. You execute a given objective "
    "end-to-end with NO human in the loop and you NEVER ask questions.\n\n"
    "Your primary capability is a real web browser, driven via the `browse` "
    "tool -- use it heavily and smartly:\n"
    "- browse('navigate', url=...) opens a page.\n"
    "- browse('read', url=...) reads a page as clean article markdown with "
    "in-content links -- this is your main way to ABSORB a page.\n"
    "- browse('links') lists in-content links so you know what to open next.\n"
    "- browse('snapshot') shows interactive elements for DRIVING the page; "
    "browse('click', ...) / browse('scroll', ...) / browse('newtab', ...) act "
    "on it. Paginate or scroll until you have the required item count.\n\n"
    "Work in two beats: (1) gather ALL requested data by actually visiting and "
    "reading the source(s) -- never guess or fabricate, only report what you "
    "read; (2) write ONE complete executive markdown report to the exact path "
    "you are given, using write_file. Do not stop until the report is written, "
    "and never write a stub or placeholder."
)

_REPORT_STRUCTURE = (
    "REQUIRED REPORT STRUCTURE (markdown):\n"
    "- `# <Title>` -- a clear title for the report.\n"
    "- A short metadata block: generated timestamp, the source URL(s), and the "
    "original task.\n"
    "- `## Executive Summary` -- 3-6 sentences on what was gathered and the "
    "headline takeaways.\n"
    "- `## Methodology` -- the plan that was followed and how the data was "
    "collected.\n"
    "- `## Findings` -- the items as a numbered list or table with the per-item "
    "fields (e.g. for Hacker News: rank, title, link, points, comments).\n"
    "- `## Key Themes & Insights` -- grouped analysis across the items.\n"
    "- `## Top Highlights` -- the most notable items and why.\n"
    "- A footer line noting the report was generated by `supporter-worker`.\n"
    "Make it a genuine, detailed executive report."
)


def _slugify(task: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", task.lower()).strip("-")[:50].strip("-")
    return slug or "task"


def _report_path(task: str, report_dir: Path | None) -> Path:
    base = report_dir or (Path(config.allowed_directories[0]) / "reports")
    stamp = datetime.now().strftime("%Y%m%d-%H%M%S")
    return base / f"{_slugify(task)}-{stamp}.md"


def _report_ready(path: Path) -> bool:
    try:
        return path.is_file() and path.stat().st_size > _MIN_REPORT_BYTES
    except OSError:
        return False


def _approve_write(path: Path, diff: str) -> bool:
    """Headless auto-approve for write_file (sync callback)."""
    return True


async def _approve_browse(title: str, message: str) -> bool:
    """Headless auto-approve for sensitive browser actions (async callback)."""
    return True


def _install_headless_callbacks() -> Callable[[], None]:
    """Register auto-approve callbacks so writes and browser actions never block
    on interactive confirmation in headless mode.

    The confirmation callbacks are process-global, so this snapshots the prior
    callbacks and returns a restore fn -- the caller MUST call it on teardown so
    a worker run inside a live process can never permanently weaken the TUI's
    interactive confirmation gates."""
    prev_write = file_ops._CONFIRMATION_CALLBACK
    prev_browse = guardrails.browse_confirmation_callback
    file_ops.register_confirmation_callback(_approve_write)
    guardrails.register_browse_callback(confirmation=_approve_browse)

    def _restore() -> None:
        file_ops.register_confirmation_callback(prev_write)
        guardrails.register_browse_callback(confirmation=prev_browse)

    return _restore


def _planner_profile() -> dict[str, Any]:
    roster = getattr(config, "delegate_agent_roster", None) or {}
    profile = roster.get("worker_planner")
    if profile is None:
        from .prompts import DELEGATE_AGENT_ROSTER

        profile = DELEGATE_AGENT_ROSTER["worker_planner"]
    return profile


async def make_plan(
    objective: str, persona: str, model: str, tools_roster: str = ""
) -> str:
    """Shared planner: ask a model with *persona* to plan *objective*.

    When *tools_roster* is given, the planner is told exactly which tools the
    orchestrator has so the plan is grounded in real capabilities.

    Returns the plan text, or empty string on failure. Never raises.
    """
    try:
        provider = get_provider(model_name=model, shared=False)
        options = GenOptions(system_instruction=persona)
        prompt = f"OBJECTIVE:\n{objective}"
        if tools_roster:
            prompt = (
                "ORCHESTRATOR TOOLS (the executor has exactly these — plan using "
                f"only them):\n{tools_roster}\n\n{prompt}"
            )
        result = await provider.generate(prompt, options)
        plan = (getattr(result, "text", "") or "").strip()
        logger.info(f"planner produced a {len(plan)}-char plan")
        return plan
    except Exception as exc:
        logger.warning(f"planner failed: {exc}")
        return ""


async def format_response(text: str, model: str) -> str:
    """Reformat an assistant reply via the fallback model. Returns the
    formatted text, or "" on failure/empty (caller keeps the raw text).
    Never raises."""
    from .prompts import RESPONSE_FORMATTER_PERSONA

    try:
        provider = get_provider(model_name=model, shared=False)
        options = GenOptions(system_instruction=RESPONSE_FORMATTER_PERSONA)
        result = await provider.generate(text, options)
        return (getattr(result, "text", "") or "").strip()
    except Exception as exc:
        logger.warning(f"format_response failed: {exc}")
        return ""


async def verify_plan(
    objective: str, plan: str, result: str, model: str
) -> tuple[bool, str]:
    """Ask the planner to verify *result* fulfils *plan* for *objective*.

    Returns (is_done, reason). Fail-open: on any error or an unclear verdict
    returns (True, ...) so a verifier outage never traps the worker loop.
    Never raises.
    """
    from .prompts import PLAN_VERIFIER_PERSONA

    try:
        provider = get_provider(model_name=model, shared=False)
        options = GenOptions(system_instruction=PLAN_VERIFIER_PERSONA)
        prompt = (
            f"OBJECTIVE:\n{objective}\n\n"
            f"PLAN:\n{plan or '(no plan was produced)'}\n\n"
            f"RESULT:\n{result}"
        )
        gen = await provider.generate(prompt, options)
        text = (getattr(gen, "text", "") or "").strip()
        first = text.splitlines()[0].upper() if text else ""
        reason = text.split("\n", 1)[1].strip() if "\n" in text else text
        if "NOT_DONE" in first or "NOT DONE" in first:
            return False, reason or "planner judged the result incomplete"
        if "DONE" in first:
            return True, reason or "planner verified the result"
        logger.info("verify_plan: no clear verdict, accepting (fail-open)")
        return True, "verifier returned no clear verdict; accepting"
    except Exception as exc:
        logger.warning(f"verify_plan failed: {exc}")
        return True, f"verify unavailable: {exc}"


async def _make_plan(task: str) -> str:
    """Phase 1: ask the heavy-model planner role for an execution plan."""
    profile = _planner_profile()
    return await make_plan(task, profile["persona"], profile["model"])


def _build_executor_agent(session_id: str) -> ChatAgent:
    """Phase 2 setup: an autonomous agent with browser + write tools."""
    model = os.getenv("WORKER_EXECUTOR_MODEL") or config.gemini_model
    registry = select_tools(build_tool_catalog(include_bash=False), _EXECUTOR_TOOLS)
    # ChatAgent supplies the system_instruction per-call via GenOptions; the REST
    # factory would silently drop it here, so it is intentionally not passed.
    provider = get_provider(model_name=model, registry=registry, shared=False)
    return ChatAgent(
        provider,
        registry=registry,
        use_search=False,
        use_code_execution=False,
        system_instruction=EXECUTOR_SYSTEM_INSTRUCTION,
        session_id=session_id,
    )


def _build_executor_prompt(task: str, plan: str, report_path: Path) -> str:
    return (
        "You are running as an autonomous worker. Execute the objective "
        "end-to-end now.\n\n"
        f"OBJECTIVE:\n{task}\n\n"
        "PLAN (from the planner -- follow it):\n"
        f"{plan or '(no plan provided; use your judgment)'}\n\n"
        "EXECUTION RULES:\n"
        "- Drive the browser HEAVILY via the browse tool to actually visit and "
        "READ the source(s); paginate/scroll to reach the required item count.\n"
        "- Gather ALL requested data first; only report what you actually read.\n"
        f"- When the data is complete, write the FINAL report to this EXACT "
        f"path via write_file(path='{report_path}', content=<full markdown>).\n\n"
        f"{_REPORT_STRUCTURE}"
    )


def _continuation_prompt(report_path: Path) -> str:
    return (
        "Continue executing the plan. You have NOT yet written the final report "
        f"to {report_path}. Keep driving the browser to gather any remaining "
        "data, then write the complete executive markdown report to that exact "
        f"path via write_file(path='{report_path}', content=<full markdown>)."
    )


def _verification_prompt(report_path: Path, reason: str) -> str:
    return (
        "The planner reviewed your report and judged it NOT done:\n"
        f"{reason}\n\n"
        "Fix exactly that gap: keep driving the browser to gather the missing or "
        f"corrected data, then rewrite the COMPLETE report to {report_path} via "
        "write_file(path=..., content=<full markdown>)."
    )


def _replan_prompt(report_path: Path, replan_ctx: ReplanContext) -> str:
    """Format a replan prompt when the executor's result fails verification.

    ponytail: Replan message goes to the *executor* (who then drives browser
    per the revised plan). Caller (run_worker) regenerates the plan and feeds
    the revised plan back to executor.
    """
    last_failure = replan_ctx.failures[-1] if replan_ctx.failures else "No feedback"
    return (
        f"The planner reviewed your report and judged "
        f"it NOT done:\n{last_failure}\n\n"
        "Keep driving the browser to address the gaps, then rewrite the COMPLETE "
        f"report to {report_path} via write_file(path=..., content=<full markdown>)."
    )


async def _teardown(agent: ChatAgent | None) -> None:
    try:
        await close_session(force=True)
    except Exception as exc:  # best-effort teardown
        logger.debug(f"worker: close_session error: {exc}")
    provider = getattr(agent, "provider", None)
    close = getattr(provider, "close", None)
    if close is None:
        return
    try:
        result = close()
        if hasattr(result, "__await__"):
            await result
    except Exception as exc:  # best-effort teardown
        logger.debug(f"worker: provider close error: {exc}")


async def run_worker(
    task: str,
    *,
    report_dir: Path | None = None,
    max_executor_turns: int = _DEFAULT_MAX_TURNS,
) -> Path:
    """Plan the task, drive the browser to fulfil it, and write an executive
    markdown report. Returns the report path. Raises ``RuntimeError`` if no
    report was produced within ``max_executor_turns``.

    Implements G2 replan loop:
    - PLAN → IMPLEMENT → VERIFY
    - If VERIFY fails, REPLAN with failure context and try again
      (max replan_max_cycles).
    """
    task = task.strip()
    if not task:
        raise ValueError("task must be a non-empty string")

    restore_callbacks = _install_headless_callbacks()
    agent: ChatAgent | None = None
    report_path = _report_path(task, report_dir)
    try:
        report_path.parent.mkdir(parents=True, exist_ok=True)
        logger.info(f"worker: task={task!r} -> report {report_path}")

        profile = _planner_profile()
        planner_model = profile["model"]

        # G2: Replan loop context
        replan_ctx = ReplanContext(task, max_cycles=config.replan_max_cycles)

        verified = False
        # Outer loop: replan cycles (G2)
        while replan_ctx.next_cycle():
            logger.info(
                f"worker: replan cycle {replan_ctx.cycle}/{config.replan_max_cycles}"
            )

            # Phase 1: PLAN
            if replan_ctx.cycle == 1:
                # Initial plan
                plan = await make_plan(task, profile["persona"], planner_model)
                logger.info(f"worker: initial plan ({len(plan)} chars)")
            else:
                # Revised plan (replan)
                logger.info(f"worker: replanning (cycle {replan_ctx.cycle})...")
                revised_prompt = replan_ctx.format_replan_prompt_context()
                plan = await make_plan(
                    revised_prompt, profile["persona"], planner_model
                )
                logger.info(f"worker: revised plan ({len(plan)} chars)")

            replan_ctx.plan = plan
            session_id = f"worker-{datetime.now().strftime('%Y%m%d-%H%M%S-%f')}"
            agent = _build_executor_agent(session_id)

            if replan_ctx.cycle == 1:
                prompt = _build_executor_prompt(task, plan, report_path)
            else:
                prompt = _replan_prompt(report_path, replan_ctx)

            # Phase 2: IMPLEMENT (executor turns)
            for turn in range(1, max_executor_turns + 1):
                logger.info(
                    f"worker: executor turn {turn}/{max_executor_turns} "
                    f"(replan cycle {replan_ctx.cycle})"
                )
                try:
                    await agent.execute(prompt)
                except Exception as exc:  # keep driving on transient turn failure
                    logger.warning(f"worker: executor turn {turn} errored: {exc}")

                if _report_ready(report_path):
                    # Report created; break executor loop to verify
                    break
                prompt = _continuation_prompt(report_path)
            else:
                logger.warning(
                    f"worker: exhausted executor turns in cycle {replan_ctx.cycle}"
                )

            # Phase 3: VERIFY
            if _report_ready(report_path):
                try:
                    result_text = report_path.read_text(encoding="utf-8")
                except OSError:
                    result_text = ""

                replan_ctx.last_result = result_text
                ok, reason = await verify_plan(task, plan, result_text, planner_model)
                if ok:
                    logger.info(
                        f"worker: planner verified report in cycle {replan_ctx.cycle}"
                    )
                    verified = True
                    break
                # Verification failed; record and continue replan loop
                logger.info(
                    f"worker: planner says NOT done in cycle {replan_ctx.cycle}: "
                    f"{reason}"
                )
                replan_ctx.record_failure(reason)
            else:
                # No report produced in this cycle; stop replanning
                logger.warning(
                    f"worker: no report after executor turns in cycle "
                    f"{replan_ctx.cycle}; stopping replan loop"
                )
                break

            await _teardown(agent)
            agent = None

        if not verified:
            logger.warning(
                f"worker: exhausted replan cycles ({config.replan_max_cycles}) "
                "without verified report"
            )
    finally:
        if agent is not None:
            await _teardown(agent)
        restore_callbacks()

    if not _report_ready(report_path):
        raise RuntimeError(f"worker did not produce a report at {report_path}")
    if not verified:
        raise RuntimeError(
            f"worker produced a report at {report_path} but exhausted replan "
            f"cycles ({config.replan_max_cycles}) without verification"
        )
    logger.info(f"worker: done -> {report_path}")
    return report_path


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="supporter-worker",
        description=(
            "Autonomous worker: plan a task, drive the browser, and write an "
            "executive markdown report."
        ),
    )
    parser.add_argument(
        "task", nargs="*", help='the task, e.g. "open hackernews and get 50 news"'
    )
    parser.add_argument(
        "--report-dir",
        dest="report_dir",
        default=None,
        help="directory for the report (default: <project>/reports)",
    )
    parser.add_argument(
        "--max-turns",
        dest="max_turns",
        type=int,
        default=_DEFAULT_MAX_TURNS,
        help="max executor turns before giving up",
    )
    args = parser.parse_args(argv)

    task = " ".join(args.task).strip()
    if not task:
        sys.stderr.write('error: no task provided\nusage: supporter-worker "<task>"\n')
        return 2

    report_dir = Path(args.report_dir) if args.report_dir else None
    try:
        path = asyncio.run(
            run_worker(task, report_dir=report_dir, max_executor_turns=args.max_turns)
        )
    except Exception as exc:
        logger.error(f"worker failed: {exc}")
        sys.stderr.write(f"error: {exc}\n")
        return 1

    sys.stdout.write(f"{path}\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
